// Home Sensor Network
// Copyright (C) 2021 Steven Giacomelli (steve@giacomelli.ca)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
// web_server_ssh.h defines the ssl server certificates.
//
// DO NOT EDIT -- this file is autogenerated
//
// DO NOT USE AS IS -- regenerate certificates with
// /scripts/cert-gen/generate.sh

#pragma once
#include <Arduino.h>

namespace web_server_cert {
static const char cert[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIID6jCCAtKgAwIBAgIUNykxtAoZmUa7wL4JshVUKnNbjXQwDQYJKoZIhvcNAQEL
BQAwWzELMAkGA1UEBhMCQ0ExDzANBgNVBAgTBlF1ZWJlYzERMA8GA1UEBxMITW9u
dHJlYWwxDDAKBgNVBAoTA0lPVDEMMAoGA1UECxMDSU9UMQwwCgYDVQQDEwNJT1Qw
HhcNMjEwODE4MDkxNzAwWhcNMjIwODE4MDkxNzAwWjBpMQswCQYDVQQGEwJDQTEP
MA0GA1UECBMGUXVlYmVjMREwDwYDVQQHEwhNb250cmVhbDEMMAoGA1UEChMDSU9U
MRMwEQYDVQQLEwpJT1QtU0VSVkVSMRMwEQYDVQQDDAppb3Rfc2VydmVyMIIBIjAN
BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyM22pL0qnNmlH9V0UYle+I/ue+74
imfgwrDaTmb0quCM7gl6YfgDbHAZNreqWIQ4RDnGhWD0HnqacuMzrdOtfQW35e2c
DhcVmm47z78PIc1XBgwR0y3ywD5W9Koo0JpfiztqCHrYpsj7aZ34maOEzB2irdhu
JZraWz1ehAtruWc8GQWZ+RKdDeOnjQvoikCJqTUvvEuty5MgGirx1iKedfcdWwdI
zN0RGGyPtvltOGobhEWBy3E9XppKMtVeVgQ4qxAQJsgVQBIIlaGc0QHPkGZLtvV2
RX+uxLJ/fQREeWZ22XVbgTio1gMEu69sZ7HpE3oshtCvrM1U11PNFIB89QIDAQAB
o4GXMIGUMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYB
BQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUJPnWKJeBysve7z1hlSXbsh6H
M8MwHwYDVR0jBBgwFoAUNUOaYzsrNJuccULX1TqJ4HFhxigwFQYDVR0RBA4wDIIK
aW90X3NlcnZlcjANBgkqhkiG9w0BAQsFAAOCAQEAsaxQcgwAHkuZL5Qp8r8HLRi+
QMOiJbd7i0JwM95qqE1fWk6yLGvwIiLx0d3K8R96UId7aKs5Y2wlMNcCes/i2iuA
TA+hbr5YgYJnbEUmlUDEuR2hop4aYdFV35RPQwbCPrjHj/5eaWrtz8n8pqBJvqOC
02uiTSbZiqAj0UeL2lVi+zYwOij2985cuPlZ2n5C9a9mGzFUKUC8MtV//R9SWFWL
Qy2g3rCD/Owo+EOSfkSh/c/CQbIyW8U9UAo+EG9eKlqxNzZmc1+FFo735KUvFxcc
B4wuX625du8NdVfTxLhTNN6PfNem8zStxLe5ELM46P9lWfDfIT/ePyQvpJ52RQ==
-----END CERTIFICATE-----
)EOF";
static const char key[] PROGMEM = R"EOF(
-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAyM22pL0qnNmlH9V0UYle+I/ue+74imfgwrDaTmb0quCM7gl6
YfgDbHAZNreqWIQ4RDnGhWD0HnqacuMzrdOtfQW35e2cDhcVmm47z78PIc1XBgwR
0y3ywD5W9Koo0JpfiztqCHrYpsj7aZ34maOEzB2irdhuJZraWz1ehAtruWc8GQWZ
+RKdDeOnjQvoikCJqTUvvEuty5MgGirx1iKedfcdWwdIzN0RGGyPtvltOGobhEWB
y3E9XppKMtVeVgQ4qxAQJsgVQBIIlaGc0QHPkGZLtvV2RX+uxLJ/fQREeWZ22XVb
gTio1gMEu69sZ7HpE3oshtCvrM1U11PNFIB89QIDAQABAoIBAQCAuT7IRGu4uNzd
l1xFmKZE+R+MWxkAwK6Yn/6SG/XkRKaTQYgunWq0bPf816hfrgLT2aWlgw17LGUu
GO/cEsI4Tx4gSz2q2qmCof+9oWD17khHHB2hHudqzYu4tAwODagJ/UBvxzBzWouw
nQ/sjaJnpufOQdv6R1aK/sBELX4VDzHmY0h9NmX8ZQTxjGIJ4ub4FK3DDFJKn/i6
jP23orX5hYx9ylBfuJ1fq5bfvSr3jMm6W0Ya77pI1QdY3m4+/ZM9LxBBbynZvjQR
Jq3jJokZ5TbHqnTgP8BLsMAJ7iMxAAfSThliqLyiBzuIAllBqEioIp5qNpjZ5NzH
+KF7m/3RAoGBAOnyQF3Rp5GaWjYyed66TrnlXsSPNf7nSmTa18DUFOkI1VRM6M99
lJU6xCcDOu8wk3h0I0jbC8S17Dj4tu1u8eJpOJLWePbG3CdF3vWlsH9ma1L8omCU
xuOKgc89bQsp5SmCoAnrJUEW0a3CTizbCQ5hdYukx0bARuGMTREAIuqLAoGBANu7
o7pDEKWAlUGKbtIH4IyxqB8Ij00cFjVFxgo/40OGdZ6fwspEhzdAV547Q2MeC2xZ
P+H7ys+Y9oF1Ko9vQAyIj6BPzP2coCPCTSbgtM5k7Ust/vd/s7JFkQQgmR5CvOQ5
bTHlOsYIb/itATT+16NjZFqbkL1s8PkHL1U4SKZ/AoGAMYz+9yAl5uAThXExgOxj
KlqbtPREUoY4qp3znsMM3sLhNGbJ1NDbfLQiwcScYfce9R9cLd0/Y93Id9SuIiIi
l3sD4Y4Ntu8tyB+zdsIuXP2bc8tQtTYt3hoDHpr7EqdAA4fIT/F/RYcIyE3kcvm9
tE8OL5KqJqEpIjKuTBCEVLsCgYB97nRPc9A+igsAnQ4WYV1YRRlNb+JxFv/DWFG/
3g2pzY3rczR4J/42tDGDBgQA8l8poZzzLxN1Fv1wBG539hKHHFz0S8f4MaO12s3M
0kvNXhqBU8MkpZOfQC90ZhpbNXR8eE0Uo4Ojq4JAyyY98TA0++mv5Ch358/TaUK/
XJqGkQKBgQCEvnU5nWfanHWncvToXY9jnaHKxiimi+QTNXd68ksE7IMNwajYHAS/
pHJIBjO9bNU8QUHeg4RYBg3+4ZSjeCdMqBQrEV6FWZ3vnXcxUNKzhyrOSYrExkPe
ln+KInoJ5WeYIZCnOGtOW47aqNnO4GeokKvS+MnD+CtfMyTSShQ1+Q==
-----END RSA PRIVATE KEY-----
)EOF";
}  // namespace web_server_cert
